server:
  port: 8080

spring:
  application:
    name: posts-api

# Configuración para el Feign Client
jsonplaceholder:
  api:
    base-url: https://jsonplaceholder.typicode.com

# Logging básico (opcional)
logging:
  level:
    com.dimension.posts: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"